"""init

Revision ID: f1823654a278
Revises: 
Create Date: 2021-10-08 16:01:50.397394

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f1823654a278'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('picture',
    sa.Column('encode', sa.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pic_addr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picture_id'), 'picture', ['id'], unique=False)
    op.create_index(op.f('ix_picture_pic_addr'), 'picture', ['pic_addr'], unique=False)
    op.create_index(op.f('ix_picture_user_id'), 'picture', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_picture_user_id'), table_name='picture')
    op.drop_index(op.f('ix_picture_pic_addr'), table_name='picture')
    op.drop_index(op.f('ix_picture_id'), table_name='picture')
    op.drop_table('picture')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
